apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: apps
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.targetport }}
    name: web
