apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-sample
  namespace: apps
  labels:
    release: prometheus # matches kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      app: monitoring-sample
  endpoints:
  - port: web
    path: /metrics
    interval: 15s
