apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: apps
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - port: 5001
    targetPort: 5001
    name: flask
